### PR TITLE
Switch netfx sample to sdk style csproj

### PR DESCRIPTION
**Pull request by jviau**

### CODE REVIEW

**Comment by jviau** [comment]
@cgillum is it okay to switch this project to `net48` as well?

**Comment by cgillum** [comment]
> @cgillum is it okay to switch this project to `net48` as well?

That’s fine by me, but any particular reason?

**Review by cgillum — APPROVED** [review]

**Comment by jviau** [comment]
> > @cgillum
> >             
> >             Chris Gillum
> >             FTE is it okay to switch this project to `net48` as well?
> 
> That’s fine by me, but any particular reason?

Mostly for convenience. I think having `net48` installed will be more common that other versions. For example, installing Visual Studio and selecting net framework will install 48. To get other versions you need to explicitly select them from the individual components section.

**Comment by cgillum** [comment]
> For example, installing Visual Studio and selecting net framework will install 48. To get other versions you need to explicitly select them from the individual components section.

That sounds like a good reason to me. Let's do it!

**Pull request merged**
