### PR TITLE
Add new packages to README.md

### PR DESCRIPTION
**Pull request by jviau**
Adds new packages to README.md.

I will be adding more detailed breaking changes in a GitHub release

### CODE REVIEW

**Comment by cgillum** [comment]
Can we also update the `<ProjectReference .../>` nodes below to point to the updated package versions?

**Comment by cgillum** [comment]
Actually, any reason not to update everything, including the code snippets? Ideally the README matches what we have published in nuget.org. The release notes can then describe changes from the old programming model.

**Comment by jviau** [comment]
Updated `<PackageReference .../>`. The code snippets in `README` were already updated in a previous PR.

**Comment by cgillum** [comment]
Sorry, I meant `<PackageReference` not `<ProjectReference`. And I was specifically referring to the contents of the README.md file, not the actual samples projects. As it stands, the contents of the README.md file are currently inconsistent with the updates you introduced in the markdown table since the rest of the README.md file refers to the older (beta) packages.

**Review by cgillum — APPROVED** [review]
Yes, this is what I had in mind. :)

**Pull request merged**
