### PR TITLE
fix CS0419 in generated code

### PR DESCRIPTION
**Pull request by cliedeman**
Ambiguous reference in cref attribute: 'TaskOrchestrationContext.CallSubOrchestratorAsync'.

### CODE REVIEW

**Comment by cliedeman** [comment]
Thanks for Approving. Will fix the test

**Comment by cliedeman** [comment]
@microsoft-github-policy-service agree

**Comment by cliedeman** [comment]
@jviau I am not able to run the unit tests locally.

image

Looks like a line ending cross platform issue

**Comment by jviau** [comment]
@cliedeman do you have `autocrlf` enabled in your .gitconfig?

**Pull request merged**
